
name: New website
on:
  push:
    branches: [main]

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
   
    environment:
      name: github pages
      url: ${{ steps.deployment.outputs.page_url }}


    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Build Images
        run: |
          docker build -t website ./frontend
          docker build -t my-website ./backend

      - name: Run Containers
        run: docker compose up -d --build


      - name: upload artifactes
        uses: actions/upload-pages-artifacts@v4
        with:
          path: "."

      - name: deploy to github pages
        uses: actions/deploy-pages@v4
